# Generated by Django 3.2.16 on 2022-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(help_text='image for the project', path='projects/img'),
        ),
    ]
