# Generated by Django 3.2.16 on 2022-10-09 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnal',
            field=models.FilePathField(default=django.utils.timezone.now, help_text='thumbnail for the project', path='static/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(help_text='image for the project', path='static/img'),
        ),
    ]
