# Generated by Django 3.2.16 on 2022-10-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20221009_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnal',
            new_name='thumbnail',
        ),
    ]
